services:
  deproxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: local_dev/deproxy
    container_name: deproxy
    ports:
      - "8080:8080"
    volumes:
      - ~/tmp/config/:/config
      - storage_volume:/storage
#      - proxy_volume:/storage/cachedir
#      - mirror_volume:/storage/mirrordir
    environment:
      - CONFIG_DIR=/config
      - STORAGE_DIR=/storage
#      - CACHE_DIR=~/tmp/storage/cachedir
#      - MIRROR_DIR=~/tmp/storage/mirrordir

volumes:
  storage_volume:
#  proxy_volume:
#  mirror_volume:
